### ISSUE TITLE
Error when video's name contains an emoji

### ISSUE THREAD

**Issue by aryuthaia** [aueangpanit/youtube-downloader-cli#5]
I'm not sure of the reason because emojis are supported file name characters in NTFS and other file systems.
This particular video's name is "🎈KAWAII FUTUREBASS for our childhood dreams that are all grown up now".
The balloon can be saved as a file name. The full log is below.

√ Please enter the YouTube video URL · https://www.youtube.com/watch?v=i1U9LM4Fip0
Downloading thumbnail...
Thumbnail downloaded successfully
Processing thumbnail...
Thumbnail processed successfully
Processing video...
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (evalmachine.<anonymous>:1
;var Xua=function(a){a=a.split("");MC["if"](a,71);MC.pn(a,3);MC.QO(a,27);MC.pn(a,2);MC["if"](a,36);MC.QO(a,14);MC.pn(a,3);MC.QO(a,68);MC.pn(a,3);return a.join("")};Xua(sig);
                                   ^

ReferenceError: MC is not defined
    at Xua (evalmachine.<anonymous>:1:36)
    at evalmachine.<anonymous>:1:165
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at decipher (C:\Users\User\AppData\Roaming\npm\node_modules\@aueangpanit\ytd-cli\node_modules\ytdl-core\lib\sig.js:88:22)
    at exports.setDownloadURL (C:\Users\User\AppData\Roaming\npm\node_modules\@aueangpanit\ytd-cli\node_modules\ytdl-core\lib\sig.js:100:31)
    at C:\Users\User\AppData\Roaming\npm\node_modules\@aueangpanit\ytd-cli\node_modules\ytdl-core\lib\sig.js:118:13
    at Array.forEach (<anonymous>)
    at exports.decipherFormats (C:\Users\User\AppData\Roaming\npm\node_modules\@aueangpanit\ytd-cli\node_modules\ytdl-core\lib\sig.js:117:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5))
    at new NodeError (node:internal/errors:393:5)
    at PassThrough.emit (node:events:502:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: evalmachine.<anonymous>:1
  ;var Xua=function(a){a=a.split("");MC["if"](a,71);MC.pn(a,3);MC.QO(a,27);MC.pn(a,2);MC["if"](a,36);MC.QO(a,14);MC.pn(a,3);MC.QO(a,68);MC.pn(a,3);return a.join("")};Xua(sig);
                                     ^

  ReferenceError: MC is not defined
      at Xua (evalmachine.<anonymous>:1:36)
      at evalmachine.<anonymous>:1:165
      at Script.runInContext (node:vm:141:12)
      at Script.runInNewContext (node:vm:146:17)
      at decipher (C:\Users\User\AppData\Roaming\npm\node_modules\@aueangpanit\ytd-cli\node_modules\ytdl-core\lib\sig.js:88:22)
      at exports.setDownloadURL (C:\Users\User\AppData\Roaming\npm\node_modules\@aueangpanit\ytd-cli\node_modules\ytdl-core\lib\sig.js:100:31)
      at C:\Users\User\AppData\Roaming\npm\node_modules\@aueangpanit\ytd-cli\node_modules\ytdl-core\lib\sig.js:118:13
      at Array.forEach (<anonymous>)
      at exports.decipherFormats (C:\Users\User\AppData\Roaming\npm\node_modules\@aueangpanit\ytd-cli\node_modules\ytdl-core\lib\sig.js:117:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}

Node.js v18.12.1

**Comment by aryuthaia** [comment]
Thanks again for your time.

**Comment by aueangpanit** [comment]
I couldn't replicate it actually. Is it still happening?

**Comment by aryuthaia** [comment]
It's now working perfectly. Thanks for checking.
